[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
bufstream = "0.1.4"
http = "1.0.0"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
ureq = {  version = "2.9.1" , features = ["json"]}
